version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: phonebookuser
      POSTGRES_PASSWORD: phonebookpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build: .
    command: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
