# Generated by Django 5.2.2 on 2025-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('key', models.CharField(help_text='Setting key', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.TextField(blank=True, help_text='Description of the setting')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting is public')),
            ],
            options={
                'verbose_name': 'Common Setting',
                'verbose_name_plural': 'Common Settings',
                'db_table': 'phone_book_common_settings',
                'ordering': ['key'],
            },
        ),
    ]
